export type ScheduleTemplateTask = {
  templateId: string;
  wbs: string;
  name: string;
  notes: string;
  categoryId: string;
  categoryName: string;
  parentTemplateId: string;
  taskType: "heading" | "subtask";
  order: number;
};

export type ScheduleTemplateCategory = {
  id: string;
  wbs: string;
  name: string;
  taskCount: number;
};

export const SCHEDULE_TEMPLATE_CATEGORIES = [
  {
    "id": "1-1",
    "wbs": "1.1",
    "name": "งานเตรียมการ",
    "taskCount": 12
  },
  {
    "id": "1-2",
    "wbs": "1.2",
    "name": "งานโครงสร้าง",
    "taskCount": 50
  },
  {
    "id": "1-3",
    "wbs": "1.3",
    "name": "งานโครงหลังคา",
    "taskCount": 13
  },
  {
    "id": "1-4",
    "wbs": "1.4",
    "name": "งานโรงรถ",
    "taskCount": 11
  },
  {
    "id": "1-5",
    "wbs": "1.5",
    "name": "งานสถาปัตยกรรมตกแต่ง",
    "taskCount": 73
  },
  {
    "id": "1-6",
    "wbs": "1.6",
    "name": "งานระบบไฟฟ้าภายใน",
    "taskCount": 18
  },
  {
    "id": "1-7",
    "wbs": "1.7",
    "name": "งานระบบสุขาภิบาล",
    "taskCount": 18
  },
  {
    "id": "1-8",
    "wbs": "1.8",
    "name": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "taskCount": 6
  },
  {
    "id": "1-9",
    "wbs": "1.9",
    "name": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "taskCount": 7
  },
  {
    "id": "1-10",
    "wbs": "1.10",
    "name": "งานสี และเก็บความเรียบร้อย",
    "taskCount": 11
  },
  {
    "id": "1-11",
    "wbs": "1.11",
    "name": "งานทำความสะอาดและส่งมอบ",
    "taskCount": 10
  },
  {
    "id": "1-12",
    "wbs": "1.12",
    "name": "งานส่งมอบบ้าน",
    "taskCount": 1
  },
  {
    "id": "1-13",
    "wbs": "1.13",
    "name": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "taskCount": 5
  },
  {
    "id": "1-14",
    "wbs": "1.14",
    "name": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "taskCount": 20
  },
  {
    "id": "1-15",
    "wbs": "1.15",
    "name": "งานระบบลิฟท์ (ถ้ามี)",
    "taskCount": 16
  },
  {
    "id": "1-16",
    "wbs": "1.16",
    "name": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "taskCount": 15
  }
] as const satisfies readonly ScheduleTemplateCategory[];

export const SCHEDULE_TEMPLATE_TASKS = [
  {
    "templateId": "schedule-template-1-1",
    "wbs": "1.1",
    "name": "งานเตรียมการ",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 1
  },
  {
    "templateId": "schedule-template-1-1-1",
    "wbs": "1.1.1",
    "name": "เจาะสำรวจชั้นดิน",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 2
  },
  {
    "templateId": "schedule-template-1-1-2",
    "wbs": "1.1.2",
    "name": "ตีผังอาคาร และกำหนดระดับอ้างอิง",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 3
  },
  {
    "templateId": "schedule-template-1-1-3",
    "wbs": "1.1.3",
    "name": "ติดตั้งมิเตอร์น้ำชั่วคราว",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 4
  },
  {
    "templateId": "schedule-template-1-1-4",
    "wbs": "1.1.4",
    "name": "ติดตั้งมิเตอร์ไฟชั่วคราว",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 5
  },
  {
    "templateId": "schedule-template-1-1-5",
    "wbs": "1.1.5",
    "name": "สร้างแคมป์คนงาน และทำห้องน้ำชั่วคราว",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 6
  },
  {
    "templateId": "schedule-template-1-1-6",
    "wbs": "1.1.6",
    "name": "งานล้อมรั้วชั่วคราวและป้ายโครงการ",
    "notes": "",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 7
  },
  {
    "templateId": "schedule-template-1-1-7",
    "wbs": "1.1.7",
    "name": "ตรวจสอบแบบก่อสร้างล่าสุดและเอกสารอนุญาต",
    "notes": "เช็กแบบ/สัญญา/ขอบเขตงานก่อนเริ่มงาน",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 8
  },
  {
    "templateId": "schedule-template-1-1-8",
    "wbs": "1.1.8",
    "name": "เคลียร์พื้นที่ รื้อถอน และปรับพื้นที่เบื้องต้น",
    "notes": "ใช้เมื่อพื้นที่มีสิ่งปลูกสร้างเดิมหรือสิ่งกีดขวาง",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 9
  },
  {
    "templateId": "schedule-template-1-1-9",
    "wbs": "1.1.9",
    "name": "จัดทางเข้าออกหน้างานและพื้นที่กองวัสดุ",
    "notes": "กำหนดพื้นที่ทำงานให้ชัดก่อนเริ่มโครงสร้าง",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 10
  },
  {
    "templateId": "schedule-template-1-1-10",
    "wbs": "1.1.10",
    "name": "ประชุมเริ่มงานและกำหนดจุดตรวจงานหลัก",
    "notes": "Kickoff กับเจ้าของงาน/วิศวกร/ผู้รับเหมา",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 11
  },
  {
    "templateId": "schedule-template-1-1-11",
    "wbs": "1.1.11",
    "name": "จัดทำแผนความปลอดภัยและป้ายเตือนหน้างาน",
    "notes": "รวม PPE จุดอันตราย และมาตรการเข้าออกพื้นที่",
    "categoryId": "1-1",
    "categoryName": "งานเตรียมการ",
    "parentTemplateId": "schedule-template-1-1",
    "taskType": "subtask",
    "order": 12
  },
  {
    "templateId": "schedule-template-1-2",
    "wbs": "1.2",
    "name": "งานโครงสร้าง",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 13
  },
  {
    "templateId": "schedule-template-1-2-1",
    "wbs": "1.2.1",
    "name": "งานเสาเข็ม",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2",
    "taskType": "heading",
    "order": 14
  },
  {
    "templateId": "schedule-template-1-2-1-1",
    "wbs": "1.2.1.1",
    "name": "งานลงเสาเข็ม",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-1",
    "taskType": "subtask",
    "order": 15
  },
  {
    "templateId": "schedule-template-1-2-2",
    "wbs": "1.2.2",
    "name": "งานฐานราก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2",
    "taskType": "heading",
    "order": 16
  },
  {
    "templateId": "schedule-template-1-2-2-1",
    "wbs": "1.2.2.1",
    "name": "งานขุดดินฐานราก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 17
  },
  {
    "templateId": "schedule-template-1-2-2-2",
    "wbs": "1.2.2.2",
    "name": "งานเตรียมเหล็กฐานราก และเหล็กเสา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 18
  },
  {
    "templateId": "schedule-template-1-2-2-3",
    "wbs": "1.2.2.3",
    "name": "งานเทคอนกรีตหยาบและปรับทราย",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 19
  },
  {
    "templateId": "schedule-template-1-2-2-4",
    "wbs": "1.2.2.4",
    "name": "งานติดตั้งเหล็กฐานราก เข้าแบบฐานราก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 20
  },
  {
    "templateId": "schedule-template-1-2-2-5",
    "wbs": "1.2.2.5",
    "name": "งานเทคอนกรีตฐานราก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 21
  },
  {
    "templateId": "schedule-template-1-2-2-6",
    "wbs": "1.2.2.6",
    "name": "งานถอดไม้แบบฐานราก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-2",
    "taskType": "subtask",
    "order": 22
  },
  {
    "templateId": "schedule-template-1-2-3",
    "wbs": "1.2.3",
    "name": "ชั้นที่ 1",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2",
    "taskType": "heading",
    "order": 23
  },
  {
    "templateId": "schedule-template-1-2-3-1",
    "wbs": "1.2.3.1",
    "name": "งานคานและพื้นชั้นที่ 1",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3",
    "taskType": "heading",
    "order": 24
  },
  {
    "templateId": "schedule-template-1-2-3-1-1",
    "wbs": "1.2.3.1.1",
    "name": "งานปรับดินฐานราก คานและเทคอนกรีตหยาบคาน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 25
  },
  {
    "templateId": "schedule-template-1-2-3-1-2",
    "wbs": "1.2.3.1.2",
    "name": "งานเหล็กเสริมคานและพื้นหล่อในที่",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 26
  },
  {
    "templateId": "schedule-template-1-2-3-1-3",
    "wbs": "1.2.3.1.3",
    "name": "งานวาง Sleeves ท่อ",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 27
  },
  {
    "templateId": "schedule-template-1-2-3-1-4",
    "wbs": "1.2.3.1.4",
    "name": "งานไม้แบบแบบคาน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 28
  },
  {
    "templateId": "schedule-template-1-2-3-1-5",
    "wbs": "1.2.3.1.5",
    "name": "งานเทคอนกรีตคานและพื้นหล่อในที่",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 29
  },
  {
    "templateId": "schedule-template-1-2-3-1-6",
    "wbs": "1.2.3.1.6",
    "name": "งานถอดไม้แบบคาน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 30
  },
  {
    "templateId": "schedule-template-1-2-3-1-7",
    "wbs": "1.2.3.1.7",
    "name": "งานติดตั้งระบบท่อกำจัดปลวก",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 31
  },
  {
    "templateId": "schedule-template-1-2-3-1-8",
    "wbs": "1.2.3.1.8",
    "name": "งานวางแผ่นพื้นสำเร็จรูป",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 32
  },
  {
    "templateId": "schedule-template-1-2-3-1-9",
    "wbs": "1.2.3.1.9",
    "name": "งานวาง Wiremesh และเทคอนกรีตพื้น Topping",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-1",
    "taskType": "subtask",
    "order": 33
  },
  {
    "templateId": "schedule-template-1-2-3-2",
    "wbs": "1.2.3.2",
    "name": "งานเสาชั้น 1",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3",
    "taskType": "heading",
    "order": 34
  },
  {
    "templateId": "schedule-template-1-2-3-2-1",
    "wbs": "1.2.3.2.1",
    "name": "งานแนวอ้างอิง เส้นไลน์ offset",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-2",
    "taskType": "subtask",
    "order": 35
  },
  {
    "templateId": "schedule-template-1-2-3-2-2",
    "wbs": "1.2.3.2.2",
    "name": "งานประกอบเหล็กเสา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-2",
    "taskType": "subtask",
    "order": 36
  },
  {
    "templateId": "schedule-template-1-2-3-2-3",
    "wbs": "1.2.3.2.3",
    "name": "งานเข้าแบบ",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-2",
    "taskType": "subtask",
    "order": 37
  },
  {
    "templateId": "schedule-template-1-2-3-2-4",
    "wbs": "1.2.3.2.4",
    "name": "งานเทคอนกรีต",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-2",
    "taskType": "subtask",
    "order": 38
  },
  {
    "templateId": "schedule-template-1-2-3-2-5",
    "wbs": "1.2.3.2.5",
    "name": "งานถอดแบบเสา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-3-2",
    "taskType": "subtask",
    "order": 39
  },
  {
    "templateId": "schedule-template-1-2-4",
    "wbs": "1.2.4",
    "name": "ชั้นที่ 2",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2",
    "taskType": "heading",
    "order": 40
  },
  {
    "templateId": "schedule-template-1-2-4-1",
    "wbs": "1.2.4.1",
    "name": "งานคานและพื้นชั้นที่ 2",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4",
    "taskType": "heading",
    "order": 41
  },
  {
    "templateId": "schedule-template-1-2-4-1-1",
    "wbs": "1.2.4.1.1",
    "name": "งานตั้งไม้ตุ้กตา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 42
  },
  {
    "templateId": "schedule-template-1-2-4-1-2",
    "wbs": "1.2.4.1.2",
    "name": "งานเหล็กเสริมคานและพื้นหล่อในที่",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 43
  },
  {
    "templateId": "schedule-template-1-2-4-1-3",
    "wbs": "1.2.4.1.3",
    "name": "งานไม้แบบแบบคาน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 44
  },
  {
    "templateId": "schedule-template-1-2-4-1-4",
    "wbs": "1.2.4.1.4",
    "name": "งานพื้นชั้น 2 (ส่วนหล่อในที่ เช่น ห้องน้ำ/ระเบียง พร้อมฝังท่อน้ำทิ้ง/Floor Drain)",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 45
  },
  {
    "templateId": "schedule-template-1-2-4-1-5",
    "wbs": "1.2.4.1.5",
    "name": "งานเทคอนกรีตคานและพื้นหล่อในที่",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 46
  },
  {
    "templateId": "schedule-template-1-2-4-1-6",
    "wbs": "1.2.4.1.6",
    "name": "งานถอดไม้แบบคาน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 47
  },
  {
    "templateId": "schedule-template-1-2-4-1-7",
    "wbs": "1.2.4.1.7",
    "name": "งานวางแผ่นพื้นสำเร็จรูป",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 48
  },
  {
    "templateId": "schedule-template-1-2-4-1-8",
    "wbs": "1.2.4.1.8",
    "name": "งานวาง Wiremesh และเทคอนกรีตพื้น Topping",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 49
  },
  {
    "templateId": "schedule-template-1-2-4-1-9",
    "wbs": "1.2.4.1.9",
    "name": "งานรื้อค้ำยัน",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-1",
    "taskType": "subtask",
    "order": 50
  },
  {
    "templateId": "schedule-template-1-2-4-2",
    "wbs": "1.2.4.2",
    "name": "งานเสาชั้น 2",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4",
    "taskType": "heading",
    "order": 51
  },
  {
    "templateId": "schedule-template-1-2-4-2-1",
    "wbs": "1.2.4.2.1",
    "name": "งานแนวอ้างอิง เส้นไลน์ offset",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-2",
    "taskType": "subtask",
    "order": 52
  },
  {
    "templateId": "schedule-template-1-2-4-2-2",
    "wbs": "1.2.4.2.2",
    "name": "งานประกอบเหล็กเสา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-2",
    "taskType": "subtask",
    "order": 53
  },
  {
    "templateId": "schedule-template-1-2-4-2-3",
    "wbs": "1.2.4.2.3",
    "name": "งานเข้าแบบ",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-2",
    "taskType": "subtask",
    "order": 54
  },
  {
    "templateId": "schedule-template-1-2-4-2-4",
    "wbs": "1.2.4.2.4",
    "name": "งานเทคอนกรีต",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-2",
    "taskType": "subtask",
    "order": 55
  },
  {
    "templateId": "schedule-template-1-2-4-2-5",
    "wbs": "1.2.4.2.5",
    "name": "งานถอดแบบเสา",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4-2",
    "taskType": "subtask",
    "order": 56
  },
  {
    "templateId": "schedule-template-1-2-4-3",
    "wbs": "1.2.4.3",
    "name": "งานบันได ช่วงชั้น 1-2",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-4",
    "taskType": "subtask",
    "order": 57
  },
  {
    "templateId": "schedule-template-1-2-5",
    "wbs": "1.2.5",
    "name": "งานตรวจสอบคุณภาพโครงสร้าง",
    "notes": "หมวดเสริมสำหรับใช้เป็น checklist ก่อน/หลังเทคอนกรีต",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2",
    "taskType": "heading",
    "order": 58
  },
  {
    "templateId": "schedule-template-1-2-5-1",
    "wbs": "1.2.5.1",
    "name": "ตรวจเหล็กเสริม แบบหล่อ ระดับ และระยะ cover ก่อนเทคอนกรีต",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-5",
    "taskType": "subtask",
    "order": 59
  },
  {
    "templateId": "schedule-template-1-2-5-2",
    "wbs": "1.2.5.2",
    "name": "ตรวจ Sleeves และงานระบบที่ฝังในคอนกรีตก่อนเท",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-5",
    "taskType": "subtask",
    "order": 60
  },
  {
    "templateId": "schedule-template-1-2-5-3",
    "wbs": "1.2.5.3",
    "name": "ทดสอบคอนกรีตหน้างานและเก็บตัวอย่างลูกปูน (ถ้ามี)",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-5",
    "taskType": "subtask",
    "order": 61
  },
  {
    "templateId": "schedule-template-1-2-5-4",
    "wbs": "1.2.5.4",
    "name": "บ่มคอนกรีตและตรวจสภาพหลังถอดแบบ",
    "notes": "",
    "categoryId": "1-2",
    "categoryName": "งานโครงสร้าง",
    "parentTemplateId": "schedule-template-1-2-5",
    "taskType": "subtask",
    "order": 62
  },
  {
    "templateId": "schedule-template-1-3",
    "wbs": "1.3",
    "name": "งานโครงหลังคา",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 63
  },
  {
    "templateId": "schedule-template-1-3-1",
    "wbs": "1.3.1",
    "name": "งานตั้งนั่งร้าน และท้องคานอเส",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 64
  },
  {
    "templateId": "schedule-template-1-3-2",
    "wbs": "1.3.2",
    "name": "งานเสริมเหล็กคานอเส",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 65
  },
  {
    "templateId": "schedule-template-1-3-3",
    "wbs": "1.3.3",
    "name": "งานไม้แบบคานอเส",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 66
  },
  {
    "templateId": "schedule-template-1-3-4",
    "wbs": "1.3.4",
    "name": "งานเทคานอเส",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 67
  },
  {
    "templateId": "schedule-template-1-3-5",
    "wbs": "1.3.5",
    "name": "งานถอดไม้แบบคานอเส",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 68
  },
  {
    "templateId": "schedule-template-1-3-6",
    "wbs": "1.3.6",
    "name": "งานติดตั้งโครงหลังคาเหล็ก/สำเร็จรูป",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 69
  },
  {
    "templateId": "schedule-template-1-3-7",
    "wbs": "1.3.7",
    "name": "งานมุงหลังคา และติดตั้งฉนวนกันความร้อน",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 70
  },
  {
    "templateId": "schedule-template-1-3-8",
    "wbs": "1.3.8",
    "name": "งานติดตั้งเชิงชาย ปั้นลม และอุปกรณ์ปิดขอบหลังคา",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 71
  },
  {
    "templateId": "schedule-template-1-3-9",
    "wbs": "1.3.9",
    "name": "งานติดตั้งครอบหลังคา ปิดลอน และอุปกรณ์กันนก",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 72
  },
  {
    "templateId": "schedule-template-1-3-10",
    "wbs": "1.3.10",
    "name": "งานติดตั้ง Flashing จุดชนผนัง/รางน้ำ/แนวเสี่ยงรั่ว",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 73
  },
  {
    "templateId": "schedule-template-1-3-11",
    "wbs": "1.3.11",
    "name": "งานติดตั้งรางน้ำและท่อน้ำฝน (ถ้ามี)",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 74
  },
  {
    "templateId": "schedule-template-1-3-12",
    "wbs": "1.3.12",
    "name": "ทดสอบรั่วซึมหลังคาและเก็บรายละเอียด",
    "notes": "",
    "categoryId": "1-3",
    "categoryName": "งานโครงหลังคา",
    "parentTemplateId": "schedule-template-1-3",
    "taskType": "subtask",
    "order": 75
  },
  {
    "templateId": "schedule-template-1-4",
    "wbs": "1.4",
    "name": "งานโรงรถ",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 76
  },
  {
    "templateId": "schedule-template-1-4-1",
    "wbs": "1.4.1",
    "name": "งานเสาเข็ม",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 77
  },
  {
    "templateId": "schedule-template-1-4-2",
    "wbs": "1.4.2",
    "name": "งานฐานราก",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 78
  },
  {
    "templateId": "schedule-template-1-4-3",
    "wbs": "1.4.3",
    "name": "งานคานคอดิน",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 79
  },
  {
    "templateId": "schedule-template-1-4-4",
    "wbs": "1.4.4",
    "name": "งานประกอบเหล็กพื้น คาน",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 80
  },
  {
    "templateId": "schedule-template-1-4-5",
    "wbs": "1.4.5",
    "name": "งานประกอบไม้แบบคาน และพื้น",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 81
  },
  {
    "templateId": "schedule-template-1-4-6",
    "wbs": "1.4.6",
    "name": "งานเทคอนกรีตคานและพื้น",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 82
  },
  {
    "templateId": "schedule-template-1-4-7",
    "wbs": "1.4.7",
    "name": "ถอดไม้แบบข้างคาน",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 83
  },
  {
    "templateId": "schedule-template-1-4-8",
    "wbs": "1.4.8",
    "name": "งานเสา",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 84
  },
  {
    "templateId": "schedule-template-1-4-9",
    "wbs": "1.4.9",
    "name": "งานประกอบโครงสร้างอะเสเหล็ก",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 85
  },
  {
    "templateId": "schedule-template-1-4-10",
    "wbs": "1.4.10",
    "name": "งานมุงหลังคา",
    "notes": "",
    "categoryId": "1-4",
    "categoryName": "งานโรงรถ",
    "parentTemplateId": "schedule-template-1-4",
    "taskType": "subtask",
    "order": 86
  },
  {
    "templateId": "schedule-template-1-5",
    "wbs": "1.5",
    "name": "งานสถาปัตยกรรมตกแต่ง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 87
  },
  {
    "templateId": "schedule-template-1-5-1",
    "wbs": "1.5.1",
    "name": "งานผนังและฉาบปูน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 88
  },
  {
    "templateId": "schedule-template-1-5-1-1",
    "wbs": "1.5.1.1",
    "name": "ชั้น 1",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1",
    "taskType": "heading",
    "order": 89
  },
  {
    "templateId": "schedule-template-1-5-1-1-1",
    "wbs": "1.5.1.1.1",
    "name": "หาเส้นไลน์ก่ออิฐ (เสาเอ็นทับหลัง / ประตู / หน้าต่าง )",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 90
  },
  {
    "templateId": "schedule-template-1-5-1-1-2",
    "wbs": "1.5.1.1.2",
    "name": "งานก่ออิฐ (เสาเอ็นทับหลัง)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 91
  },
  {
    "templateId": "schedule-template-1-5-1-1-3",
    "wbs": "1.5.1.1.3",
    "name": "งานติดตั้งสุขภัณฑ์และอุปกรณ์ (Second fix)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 92
  },
  {
    "templateId": "schedule-template-1-5-1-1-4",
    "wbs": "1.5.1.1.4",
    "name": "งานติดตั้งนั่งร้านรอบอาคาร",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 93
  },
  {
    "templateId": "schedule-template-1-5-1-1-5",
    "wbs": "1.5.1.1.5",
    "name": "งานฉาบปูนภายใน + จับเซี้ยม + ตาข่าย",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 94
  },
  {
    "templateId": "schedule-template-1-5-1-1-6",
    "wbs": "1.5.1.1.6",
    "name": "งานฉาบบันได ปรับลูกตั้ง-ลูกนอน และฉาบตกแต่งหน้าบ้าน/เฉลียง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-1",
    "taskType": "subtask",
    "order": 95
  },
  {
    "templateId": "schedule-template-1-5-1-2",
    "wbs": "1.5.1.2",
    "name": "ชั้น 2",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1",
    "taskType": "heading",
    "order": 96
  },
  {
    "templateId": "schedule-template-1-5-1-2-1",
    "wbs": "1.5.1.2.1",
    "name": "หาเส้นไลน์ก่ออิฐ (เสาเอ็นทับหลัง / ประตู / หน้าต่าง )",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-2",
    "taskType": "subtask",
    "order": 97
  },
  {
    "templateId": "schedule-template-1-5-1-2-2",
    "wbs": "1.5.1.2.2",
    "name": "งานก่ออิฐ (เสาเอ็นทับหลัง)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-2",
    "taskType": "subtask",
    "order": 98
  },
  {
    "templateId": "schedule-template-1-5-1-2-3",
    "wbs": "1.5.1.2.3",
    "name": "งานติดตั้งสุขภัณฑ์และอุปกรณ์ (Second fix)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-2",
    "taskType": "subtask",
    "order": 99
  },
  {
    "templateId": "schedule-template-1-5-1-2-4",
    "wbs": "1.5.1.2.4",
    "name": "งานฉาบปูนภายใน + จับเซี้ยม + ตาข่าย",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-2",
    "taskType": "subtask",
    "order": 100
  },
  {
    "templateId": "schedule-template-1-5-1-2-5",
    "wbs": "1.5.1.2.5",
    "name": "งานฉาบบันได ปรับลูกตั้ง-ลูกนอน และฉาบตกแต่งหน้าบ้าน/เฉลียง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1-2",
    "taskType": "subtask",
    "order": 101
  },
  {
    "templateId": "schedule-template-1-5-1-3",
    "wbs": "1.5.1.3",
    "name": "งานฉาบภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1",
    "taskType": "subtask",
    "order": 102
  },
  {
    "templateId": "schedule-template-1-5-1-4",
    "wbs": "1.5.1.4",
    "name": "งานติดตั้งบัวปูนปั้น (ภายนอก)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1",
    "taskType": "subtask",
    "order": 103
  },
  {
    "templateId": "schedule-template-1-5-1-5",
    "wbs": "1.5.1.5",
    "name": "งานติดตั้งไม้เทียมตกแต่งผนังภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-1",
    "taskType": "subtask",
    "order": 104
  },
  {
    "templateId": "schedule-template-1-5-2",
    "wbs": "1.5.2",
    "name": "งานกระเบื้อง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 105
  },
  {
    "templateId": "schedule-template-1-5-2-1",
    "wbs": "1.5.2.1",
    "name": "ห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2",
    "taskType": "heading",
    "order": 106
  },
  {
    "templateId": "schedule-template-1-5-2-1-1",
    "wbs": "1.5.2.1.1",
    "name": "พื้น",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1",
    "taskType": "heading",
    "order": 107
  },
  {
    "templateId": "schedule-template-1-5-2-1-1-1",
    "wbs": "1.5.2.1.1.1",
    "name": "งานระบบกันซึมพื้นห้องน้ำ/ระเบียง พร้อมขังน้ำทดสอบ (Water Ponding Test)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-1",
    "taskType": "subtask",
    "order": 108
  },
  {
    "templateId": "schedule-template-1-5-2-1-1-2",
    "wbs": "1.5.2.1.1.2",
    "name": "งานเทปรับระดับพื้น (Screed)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-1",
    "taskType": "subtask",
    "order": 109
  },
  {
    "templateId": "schedule-template-1-5-2-1-1-3",
    "wbs": "1.5.2.1.1.3",
    "name": "ติดตั้ง Floor Drain",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-1",
    "taskType": "subtask",
    "order": 110
  },
  {
    "templateId": "schedule-template-1-5-2-1-1-4",
    "wbs": "1.5.2.1.1.4",
    "name": "งานพื้นกระเบื้อง ห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-1",
    "taskType": "subtask",
    "order": 111
  },
  {
    "templateId": "schedule-template-1-5-2-1-2",
    "wbs": "1.5.2.1.2",
    "name": "ผนัง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1",
    "taskType": "heading",
    "order": 112
  },
  {
    "templateId": "schedule-template-1-5-2-1-2-1",
    "wbs": "1.5.2.1.2.1",
    "name": "งานหล่อเคาน์เตอร์ห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-2",
    "taskType": "subtask",
    "order": 113
  },
  {
    "templateId": "schedule-template-1-5-2-1-2-2",
    "wbs": "1.5.2.1.2.2",
    "name": "ฉาบผนังห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-2",
    "taskType": "subtask",
    "order": 114
  },
  {
    "templateId": "schedule-template-1-5-2-1-2-3",
    "wbs": "1.5.2.1.2.3",
    "name": "ปูผนังกระเบื้องห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-1-2",
    "taskType": "subtask",
    "order": 115
  },
  {
    "templateId": "schedule-template-1-5-2-2",
    "wbs": "1.5.2.2",
    "name": "กระเบื้องภายใน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2",
    "taskType": "heading",
    "order": 116
  },
  {
    "templateId": "schedule-template-1-5-2-2-1",
    "wbs": "1.5.2.2.1",
    "name": "งานเทปรับระดับพื้น (Screed)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-2",
    "taskType": "subtask",
    "order": 117
  },
  {
    "templateId": "schedule-template-1-5-2-2-2",
    "wbs": "1.5.2.2.2",
    "name": "งานเคาเตอร์ครัว",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-2",
    "taskType": "subtask",
    "order": 118
  },
  {
    "templateId": "schedule-template-1-5-2-2-3",
    "wbs": "1.5.2.2.3",
    "name": "งานผิวพื้นกระเบื้อง ภายในบ้าน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-2",
    "taskType": "subtask",
    "order": 119
  },
  {
    "templateId": "schedule-template-1-5-2-2-4",
    "wbs": "1.5.2.2.4",
    "name": "งานวัสดุป้องกันผิวกระเบื้อง (กระดาษลูกฟูก)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-2",
    "taskType": "subtask",
    "order": 120
  },
  {
    "templateId": "schedule-template-1-5-2-3",
    "wbs": "1.5.2.3",
    "name": "กระเบื้องภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2",
    "taskType": "heading",
    "order": 121
  },
  {
    "templateId": "schedule-template-1-5-2-3-1",
    "wbs": "1.5.2.3.1",
    "name": "งานเทปรับระดับพื้น (Screed)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-3",
    "taskType": "subtask",
    "order": 122
  },
  {
    "templateId": "schedule-template-1-5-2-3-2",
    "wbs": "1.5.2.3.2",
    "name": "งานผิวพื้นกระเบื้อง ภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-3",
    "taskType": "subtask",
    "order": 123
  },
  {
    "templateId": "schedule-template-1-5-2-3-3",
    "wbs": "1.5.2.3.3",
    "name": "งานปูผนังกระเบื้อง ภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-2-3",
    "taskType": "subtask",
    "order": 124
  },
  {
    "templateId": "schedule-template-1-5-3",
    "wbs": "1.5.3",
    "name": "งานฝ้าเพดาน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 125
  },
  {
    "templateId": "schedule-template-1-5-3-1",
    "wbs": "1.5.3.1",
    "name": "ห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 126
  },
  {
    "templateId": "schedule-template-1-5-3-2",
    "wbs": "1.5.3.2",
    "name": "งานโครงฝ้าเพดาน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 127
  },
  {
    "templateId": "schedule-template-1-5-3-3",
    "wbs": "1.5.3.3",
    "name": "งานติดแผ่นฝ้า",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 128
  },
  {
    "templateId": "schedule-template-1-5-3-4",
    "wbs": "1.5.3.4",
    "name": "ภายใน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 129
  },
  {
    "templateId": "schedule-template-1-5-3-5",
    "wbs": "1.5.3.5",
    "name": "งานโครงฝ้าเพดาน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 130
  },
  {
    "templateId": "schedule-template-1-5-3-6",
    "wbs": "1.5.3.6",
    "name": "งานติดแผ่นฝ้า",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 131
  },
  {
    "templateId": "schedule-template-1-5-3-7",
    "wbs": "1.5.3.7",
    "name": "ภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 132
  },
  {
    "templateId": "schedule-template-1-5-3-8",
    "wbs": "1.5.3.8",
    "name": "งานติดแผ่นฝ้า",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 133
  },
  {
    "templateId": "schedule-template-1-5-3-9",
    "wbs": "1.5.3.9",
    "name": "งานโครงฝ้าเพดาน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 134
  },
  {
    "templateId": "schedule-template-1-5-3-10",
    "wbs": "1.5.3.10",
    "name": "งานโครงฝ้าเพดานภายนอก (ชายคา) และติดแผ่นฝ้า/ระแนง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-3",
    "taskType": "subtask",
    "order": 135
  },
  {
    "templateId": "schedule-template-1-5-4",
    "wbs": "1.5.4",
    "name": "งานประตู-หน้าต่าง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 136
  },
  {
    "templateId": "schedule-template-1-5-4-1",
    "wbs": "1.5.4.1",
    "name": "อลูมิเนียม",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 137
  },
  {
    "templateId": "schedule-template-1-5-4-2",
    "wbs": "1.5.4.2",
    "name": "ประตูภายภายนอก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 138
  },
  {
    "templateId": "schedule-template-1-5-4-3",
    "wbs": "1.5.4.3",
    "name": "ประตูภายใน",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 139
  },
  {
    "templateId": "schedule-template-1-5-4-4",
    "wbs": "1.5.4.4",
    "name": "ประตูห้องน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 140
  },
  {
    "templateId": "schedule-template-1-5-4-5",
    "wbs": "1.5.4.5",
    "name": "วัดหน้างานและยืนยันขนาดประตู-หน้าต่างก่อนผลิต/สั่งของ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 141
  },
  {
    "templateId": "schedule-template-1-5-4-6",
    "wbs": "1.5.4.6",
    "name": "ติดตั้งวงกบ บานพับ มือจับ อุปกรณ์ล็อก และซีลแลนท์",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 142
  },
  {
    "templateId": "schedule-template-1-5-4-7",
    "wbs": "1.5.4.7",
    "name": "ทดสอบการเปิด-ปิดและตรวจรอยรั่วซึมประตู-หน้าต่าง",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-4",
    "taskType": "subtask",
    "order": 143
  },
  {
    "templateId": "schedule-template-1-5-5",
    "wbs": "1.5.5",
    "name": "งาน SPC",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 144
  },
  {
    "templateId": "schedule-template-1-5-5-1",
    "wbs": "1.5.5.1",
    "name": "งานปรับพื้น Self-leveling (สำหรับปู SPC)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-5",
    "taskType": "subtask",
    "order": 145
  },
  {
    "templateId": "schedule-template-1-5-5-2",
    "wbs": "1.5.5.2",
    "name": "งานปูพื้น SPC และติดตั้งบัวเชิงผนัง (ทำหลังงานสีรอบแรก)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-5",
    "taskType": "subtask",
    "order": 146
  },
  {
    "templateId": "schedule-template-1-5-5-3",
    "wbs": "1.5.5.3",
    "name": "งานติดตั้งลูกตั้ง-ลูกนอนบันได SPC และชานพัก",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-5",
    "taskType": "subtask",
    "order": 147
  },
  {
    "templateId": "schedule-template-1-5-6",
    "wbs": "1.5.6",
    "name": "งานกันซึมและทดสอบรั่วซึม",
    "notes": "หมวดรวมสำหรับพื้นที่เปียกและจุดเสี่ยงรั่ว",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 148
  },
  {
    "templateId": "schedule-template-1-5-6-1",
    "wbs": "1.5.6.1",
    "name": "งานกันซึมห้องน้ำและขังน้ำทดสอบ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-6",
    "taskType": "subtask",
    "order": 149
  },
  {
    "templateId": "schedule-template-1-5-6-2",
    "wbs": "1.5.6.2",
    "name": "งานกันซึมระเบียง/เฉลียง/พื้นที่ภายนอกที่รับน้ำ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-6",
    "taskType": "subtask",
    "order": 150
  },
  {
    "templateId": "schedule-template-1-5-6-3",
    "wbs": "1.5.6.3",
    "name": "งานกันซึมดาดฟ้าหรือหลังคาคอนกรีต (ถ้ามี)",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-6",
    "taskType": "subtask",
    "order": 151
  },
  {
    "templateId": "schedule-template-1-5-6-4",
    "wbs": "1.5.6.4",
    "name": "ตรวจจุดรอยต่อผนัง ช่องเปิด ท่อ และ Floor Drain",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-6",
    "taskType": "subtask",
    "order": 152
  },
  {
    "templateId": "schedule-template-1-5-7",
    "wbs": "1.5.7",
    "name": "งานบันได ราวกันตก และราวจับ",
    "notes": "ใช้เมื่อมีงานนอกเหนือจากผิว SPC/วัสดุปิดผิว",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 153
  },
  {
    "templateId": "schedule-template-1-5-7-1",
    "wbs": "1.5.7.1",
    "name": "ติดตั้งโครง/ราวกันตก/ราวจับตามแบบ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-7",
    "taskType": "subtask",
    "order": 154
  },
  {
    "templateId": "schedule-template-1-5-7-2",
    "wbs": "1.5.7.2",
    "name": "เก็บผิวบันได จมูกบันได และรอยต่อวัสดุ",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-7",
    "taskType": "subtask",
    "order": 155
  },
  {
    "templateId": "schedule-template-1-5-8",
    "wbs": "1.5.8",
    "name": "งาน Built-in ครัว และเฟอร์นิเจอร์ติดตั้งถาวร (ถ้ามี)",
    "notes": "หมวด optional เลือกใช้เฉพาะโครงการที่มีในขอบเขตงาน",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5",
    "taskType": "heading",
    "order": 156
  },
  {
    "templateId": "schedule-template-1-5-8-1",
    "wbs": "1.5.8.1",
    "name": "ตรวจขนาดหน้างานและระยะระบบก่อนผลิต Built-in",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-8",
    "taskType": "subtask",
    "order": 157
  },
  {
    "templateId": "schedule-template-1-5-8-2",
    "wbs": "1.5.8.2",
    "name": "ติดตั้งชุดครัว ตู้ Built-in และงาน Top",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-8",
    "taskType": "subtask",
    "order": 158
  },
  {
    "templateId": "schedule-template-1-5-8-3",
    "wbs": "1.5.8.3",
    "name": "เก็บสี ซิลิโคน อุปกรณ์ และตรวจการใช้งาน Built-in",
    "notes": "",
    "categoryId": "1-5",
    "categoryName": "งานสถาปัตยกรรมตกแต่ง",
    "parentTemplateId": "schedule-template-1-5-8",
    "taskType": "subtask",
    "order": 159
  },
  {
    "templateId": "schedule-template-1-6",
    "wbs": "1.6",
    "name": "งานระบบไฟฟ้าภายใน",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 160
  },
  {
    "templateId": "schedule-template-1-6-1",
    "wbs": "1.6.1",
    "name": "งานเดินท่อ (First Fix)",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "heading",
    "order": 161
  },
  {
    "templateId": "schedule-template-1-6-1-1",
    "wbs": "1.6.1.1",
    "name": "งานกรีดผนังฝังท่อร้อยสายไฟ (ทำช่วงก่ออิฐ)",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-1",
    "taskType": "subtask",
    "order": 162
  },
  {
    "templateId": "schedule-template-1-6-1-2",
    "wbs": "1.6.1.2",
    "name": "งานเดินท่อร้อยสายไฟบนฝ้าเพดาน",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-1",
    "taskType": "subtask",
    "order": 163
  },
  {
    "templateId": "schedule-template-1-6-2",
    "wbs": "1.6.2",
    "name": "งานร้อยสาย (Wiring)",
    "notes": "ทำตอนช่วงเริ่มงาน Skim",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "heading",
    "order": 164
  },
  {
    "templateId": "schedule-template-1-6-2-1",
    "wbs": "1.6.2.1",
    "name": "งานติดตั้งสายเมนภายนอก",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-2",
    "taskType": "subtask",
    "order": 165
  },
  {
    "templateId": "schedule-template-1-6-2-2",
    "wbs": "1.6.2.2",
    "name": "งานร้อยสายไฟฟ้าเข้าท่อ",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-2",
    "taskType": "subtask",
    "order": 166
  },
  {
    "templateId": "schedule-template-1-6-2-3",
    "wbs": "1.6.2.3",
    "name": "งานติดตั้งตู้ Consumer Unit (ตู้เมนไฟฟ้า)",
    "notes": "ติดตั้งหลังงานสี",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-2",
    "taskType": "subtask",
    "order": 167
  },
  {
    "templateId": "schedule-template-1-6-3",
    "wbs": "1.6.3",
    "name": "ติดตั้งอุปกรณ์ (Second Fix)",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "heading",
    "order": 168
  },
  {
    "templateId": "schedule-template-1-6-3-1",
    "wbs": "1.6.3.1",
    "name": "งานติดตั้งอุปกรณ์ไฟฟ้า (ปลั๊ก, สวิตช์, ดวงโคม)",
    "notes": "หลังงานสี",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-3",
    "taskType": "subtask",
    "order": 169
  },
  {
    "templateId": "schedule-template-1-6-4",
    "wbs": "1.6.4",
    "name": "งานเทสต์ระบบไฟฟ้า และกราวด์",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "subtask",
    "order": 170
  },
  {
    "templateId": "schedule-template-1-6-5",
    "wbs": "1.6.5",
    "name": "งานระบบสายดินและอุปกรณ์ป้องกันไฟฟ้า",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "heading",
    "order": 171
  },
  {
    "templateId": "schedule-template-1-6-5-1",
    "wbs": "1.6.5.1",
    "name": "ติดตั้งหลักดิน สายดิน และตรวจค่าความต้านทานดิน",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-5",
    "taskType": "subtask",
    "order": 172
  },
  {
    "templateId": "schedule-template-1-6-5-2",
    "wbs": "1.6.5.2",
    "name": "ติดตั้ง/ตรวจสอบ Breaker, RCD/RCBO และป้ายระบุวงจร",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-5",
    "taskType": "subtask",
    "order": 173
  },
  {
    "templateId": "schedule-template-1-6-6",
    "wbs": "1.6.6",
    "name": "งานระบบสื่อสาร Internet CCTV และ Smart Home (ถ้ามี)",
    "notes": "หมวด optional ตามขอบเขตงาน",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6",
    "taskType": "heading",
    "order": 174
  },
  {
    "templateId": "schedule-template-1-6-6-1",
    "wbs": "1.6.6.1",
    "name": "เดินท่อและสายสัญญาณ Internet/LAN/โทรศัพท์",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-6",
    "taskType": "subtask",
    "order": 175
  },
  {
    "templateId": "schedule-template-1-6-6-2",
    "wbs": "1.6.6.2",
    "name": "เดินท่อและสาย CCTV/Access Control/Smart Home",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-6",
    "taskType": "subtask",
    "order": 176
  },
  {
    "templateId": "schedule-template-1-6-6-3",
    "wbs": "1.6.6.3",
    "name": "ติดตั้งอุปกรณ์และทดสอบสัญญาณ",
    "notes": "",
    "categoryId": "1-6",
    "categoryName": "งานระบบไฟฟ้าภายใน",
    "parentTemplateId": "schedule-template-1-6-6",
    "taskType": "subtask",
    "order": 177
  },
  {
    "templateId": "schedule-template-1-7",
    "wbs": "1.7",
    "name": "งานระบบสุขาภิบาล",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 178
  },
  {
    "templateId": "schedule-template-1-7-1",
    "wbs": "1.7.1",
    "name": "งานเดินท่อใต้พื้นน้ำดี-น้ำทิ้ง",
    "notes": "เดินช่วงก่ออิฐหรือหลังจากเสร็จงานก่อ",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "subtask",
    "order": 179
  },
  {
    "templateId": "schedule-template-1-7-2",
    "wbs": "1.7.2",
    "name": "งานติดตั้งอุปกรณ์ครัว (ฮูดดูดควัน, ซิงค์ล้างจาน)",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "subtask",
    "order": 180
  },
  {
    "templateId": "schedule-template-1-7-3",
    "wbs": "1.7.3",
    "name": "งานติดตั้งสุขภัณฑ์ (ชักโครก, อ่างล้างหน้า, ฝักบัว, ก๊อกน้ำ)",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "subtask",
    "order": 181
  },
  {
    "templateId": "schedule-template-1-7-4",
    "wbs": "1.7.4",
    "name": "ทดสอบระบบทั้งหมด",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "subtask",
    "order": 182
  },
  {
    "templateId": "schedule-template-1-7-5",
    "wbs": "1.7.5",
    "name": "งานระบบระบายน้ำภายนอกและบำบัดน้ำเสีย",
    "notes": "ทำตอนที่รื้อนั่งร้าน เมื่องานสีภายนอกเก็บเรียบร้อย",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "heading",
    "order": 183
  },
  {
    "templateId": "schedule-template-1-7-5-1",
    "wbs": "1.7.5.1",
    "name": "งานติดตั้งถังบำบัดน้ำเสียสำเร็จรูป",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 184
  },
  {
    "templateId": "schedule-template-1-7-5-2",
    "wbs": "1.7.5.2",
    "name": "งานติดตั้งถังดักไขมัน",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 185
  },
  {
    "templateId": "schedule-template-1-7-5-3",
    "wbs": "1.7.5.3",
    "name": "งานวางท่อระบายน้ำใยหิน/PVC รอบบ้าน เชื่อมต่อบ่อพัก",
    "notes": "แล้วแต่ขนาดบ้าน",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 186
  },
  {
    "templateId": "schedule-template-1-7-5-4",
    "wbs": "1.7.5.4",
    "name": "งานติดตั้งบ่อพักระบายน้ำ",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 187
  },
  {
    "templateId": "schedule-template-1-7-5-5",
    "wbs": "1.7.5.5",
    "name": "งานติดตั้งปั๊มน้ำ และแทงค์น้ำ (เทคอนกรีตฐานราก)",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 188
  },
  {
    "templateId": "schedule-template-1-7-5-6",
    "wbs": "1.7.5.6",
    "name": "งานเดินท่อเมนประปาเข้าอาคาร",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 189
  },
  {
    "templateId": "schedule-template-1-7-5-7",
    "wbs": "1.7.5.7",
    "name": "งานทดสอบระบบน้ำดี-น้ำเสีย ทั้งระบบ",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-5",
    "taskType": "subtask",
    "order": 190
  },
  {
    "templateId": "schedule-template-1-7-6",
    "wbs": "1.7.6",
    "name": "งานทดสอบระบบสุขาภิบาลระหว่างก่อสร้าง",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "heading",
    "order": 191
  },
  {
    "templateId": "schedule-template-1-7-6-1",
    "wbs": "1.7.6.1",
    "name": "ทดสอบแรงดันท่อน้ำดี",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-6",
    "taskType": "subtask",
    "order": 192
  },
  {
    "templateId": "schedule-template-1-7-6-2",
    "wbs": "1.7.6.2",
    "name": "ทดสอบการรั่วซึมและความลาดเอียงท่อน้ำทิ้ง",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-6",
    "taskType": "subtask",
    "order": 193
  },
  {
    "templateId": "schedule-template-1-7-6-3",
    "wbs": "1.7.6.3",
    "name": "ตรวจตำแหน่งท่อ Vent และช่อง Service",
    "notes": "",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7-6",
    "taskType": "subtask",
    "order": 194
  },
  {
    "templateId": "schedule-template-1-7-7",
    "wbs": "1.7.7",
    "name": "งาน As-built ระบบสุขาภิบาล",
    "notes": "บันทึกแนวท่อจริงก่อนปิดผิวหรือส่งมอบ",
    "categoryId": "1-7",
    "categoryName": "งานระบบสุขาภิบาล",
    "parentTemplateId": "schedule-template-1-7",
    "taskType": "subtask",
    "order": 195
  },
  {
    "templateId": "schedule-template-1-8",
    "wbs": "1.8",
    "name": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 196
  },
  {
    "templateId": "schedule-template-1-8-1",
    "wbs": "1.8.1",
    "name": "งานตอกเข็มรั้ว (ทำพร้อมตัวบ้าน หรือมาทำทีหลังก็ได้)",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "schedule-template-1-8",
    "taskType": "subtask",
    "order": 197
  },
  {
    "templateId": "schedule-template-1-8-2",
    "wbs": "1.8.2",
    "name": "งานฐานรากและคานคอดินรั้ว",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "schedule-template-1-8",
    "taskType": "subtask",
    "order": 198
  },
  {
    "templateId": "schedule-template-1-8-3",
    "wbs": "1.8.3",
    "name": "งานตั้งเสารั้ว และก่ออิฐโชว์แนว/ฉาบปูน/ทาสี",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "schedule-template-1-8",
    "taskType": "subtask",
    "order": 199
  },
  {
    "templateId": "schedule-template-1-8-4",
    "wbs": "1.8.4",
    "name": "งานติดตั้งประตูรั้ว (เหล็ก/สแตนเลส/ไม้)",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "schedule-template-1-8",
    "taskType": "subtask",
    "order": 200
  },
  {
    "templateId": "schedule-template-1-8-5",
    "wbs": "1.8.5",
    "name": "งานติดตั้งกริ่งหน้าบ้าน ป้ายบ้านเลขที่ และไฟหัวเสา",
    "notes": "",
    "categoryId": "1-8",
    "categoryName": "งานรั้วรอบบ้านและรั้วหน้างาน",
    "parentTemplateId": "schedule-template-1-8",
    "taskType": "subtask",
    "order": 201
  },
  {
    "templateId": "schedule-template-1-9",
    "wbs": "1.9",
    "name": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 202
  },
  {
    "templateId": "schedule-template-1-9-1",
    "wbs": "1.9.1",
    "name": "งานปรับระดับดินรอบบ้าน",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 203
  },
  {
    "templateId": "schedule-template-1-9-2",
    "wbs": "1.9.2",
    "name": "งานเทคอนกรีตทางเดินรอบบ้าน (Apron)",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 204
  },
  {
    "templateId": "schedule-template-1-9-3",
    "wbs": "1.9.3",
    "name": "งานเทคอนกรีตโรงจอดรถ (ถ้าแยกจากตัวบ้าน) หรือปูกระเบื้องโรงรถ",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 205
  },
  {
    "templateId": "schedule-template-1-9-4",
    "wbs": "1.9.4",
    "name": "งานปลูกหญ้า หรือปูบล็อกตัวหนอน (ตามแบบ)",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 206
  },
  {
    "templateId": "schedule-template-1-9-5",
    "wbs": "1.9.5",
    "name": "งานระบบระบายน้ำผิวดินและปรับ slope รอบบ้าน",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 207
  },
  {
    "templateId": "schedule-template-1-9-6",
    "wbs": "1.9.6",
    "name": "งานตรวจระดับพื้นที่ภายนอกก่อนส่งมอบ",
    "notes": "",
    "categoryId": "1-9",
    "categoryName": "งานปรับภูมิทัศน์ภายนอก และบริเวณ",
    "parentTemplateId": "schedule-template-1-9",
    "taskType": "subtask",
    "order": 208
  },
  {
    "templateId": "schedule-template-1-10",
    "wbs": "1.10",
    "name": "งานสี และเก็บความเรียบร้อย",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 209
  },
  {
    "templateId": "schedule-template-1-10-1",
    "wbs": "1.10.1",
    "name": "รองพื้นและสีรอบแรก",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 210
  },
  {
    "templateId": "schedule-template-1-10-2",
    "wbs": "1.10.2",
    "name": "งานทาสีรองพื้นปูนเก่า/ใหม่ (ภายใน-ภายนอก)",
    "notes": "ทำหลัง Skim",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 211
  },
  {
    "templateId": "schedule-template-1-10-3",
    "wbs": "1.10.3",
    "name": "งานทาสีจริง รอบที่ 1 (ภายใน-ภายนอก-ฝ้า) มักทำก่อนปูพื้น SPC",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 212
  },
  {
    "templateId": "schedule-template-1-10-4",
    "wbs": "1.10.4",
    "name": "เก็บงานรอบสุดท้าย",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 213
  },
  {
    "templateId": "schedule-template-1-10-5",
    "wbs": "1.10.5",
    "name": "งานตั้งนั่งร้านรอบ 2 (เพื่อเก็บสีภายนอกรอบสุดท้าย ถ้าจำเป็น)",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 214
  },
  {
    "templateId": "schedule-template-1-10-6",
    "wbs": "1.10.6",
    "name": "งานทาสีจริง รอบที่ 2 (เก็บงานครั้งสุดท้าย)",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 215
  },
  {
    "templateId": "schedule-template-1-10-7",
    "wbs": "1.10.7",
    "name": "งานเก็บสีวงกบ บัว และรอยต่อต่างๆ",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 216
  },
  {
    "templateId": "schedule-template-1-10-8",
    "wbs": "1.10.8",
    "name": "งาน Skim Coat/โป๊วผิว และขัดแต่งก่อนทาสี",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 217
  },
  {
    "templateId": "schedule-template-1-10-9",
    "wbs": "1.10.9",
    "name": "งานป้องกันพื้น ผนัง อุปกรณ์ และงานตกแต่งก่อนทาสี",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 218
  },
  {
    "templateId": "schedule-template-1-10-10",
    "wbs": "1.10.10",
    "name": "ตรวจเฉดสี ผิวสี รอยแตกร้าว และเก็บ Touch-up",
    "notes": "",
    "categoryId": "1-10",
    "categoryName": "งานสี และเก็บความเรียบร้อย",
    "parentTemplateId": "schedule-template-1-10",
    "taskType": "subtask",
    "order": 219
  },
  {
    "templateId": "schedule-template-1-11",
    "wbs": "1.11",
    "name": "งานทำความสะอาดและส่งมอบ",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 220
  },
  {
    "templateId": "schedule-template-1-11-1",
    "wbs": "1.11.1",
    "name": "ยื่นขอบ้านเลขที่ / ไฟฟ้าถาวร / ประปาถาวร",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 221
  },
  {
    "templateId": "schedule-template-1-11-2",
    "wbs": "1.11.2",
    "name": "รื้อถอนแคมป์คนงาน และขยะก่อสร้างออกจากพื้นที่",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 222
  },
  {
    "templateId": "schedule-template-1-11-3",
    "wbs": "1.11.3",
    "name": "ทำความสะอาดใหญ่ (Big Cleaning) ขัดพื้น เช็ดกระจก",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 223
  },
  {
    "templateId": "schedule-template-1-11-4",
    "wbs": "1.11.4",
    "name": "ตรวจสอบความเรียบร้อย (Defect Checking)",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 224
  },
  {
    "templateId": "schedule-template-1-11-5",
    "wbs": "1.11.5",
    "name": "ลูกค้าตรวจรับมอบครั้งที่ 1",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 225
  },
  {
    "templateId": "schedule-template-1-11-6",
    "wbs": "1.11.6",
    "name": "แก้ไขตามรายการตรวจรับมอบ ครั้ง 1 (ถ้ามี)",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 226
  },
  {
    "templateId": "schedule-template-1-11-7",
    "wbs": "1.11.7",
    "name": "จัดทำ As-built Drawing และเอกสารส่งมอบ",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 227
  },
  {
    "templateId": "schedule-template-1-11-8",
    "wbs": "1.11.8",
    "name": "รวบรวมคู่มืออุปกรณ์ ใบรับประกัน และกุญแจ",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 228
  },
  {
    "templateId": "schedule-template-1-11-9",
    "wbs": "1.11.9",
    "name": "ตรวจ Punch List รอบสุดท้ายก่อนส่งมอบ",
    "notes": "",
    "categoryId": "1-11",
    "categoryName": "งานทำความสะอาดและส่งมอบ",
    "parentTemplateId": "schedule-template-1-11",
    "taskType": "subtask",
    "order": 229
  },
  {
    "templateId": "schedule-template-1-12",
    "wbs": "1.12",
    "name": "งานส่งมอบบ้าน",
    "notes": "",
    "categoryId": "1-12",
    "categoryName": "งานส่งมอบบ้าน",
    "parentTemplateId": "",
    "taskType": "subtask",
    "order": 230
  },
  {
    "templateId": "schedule-template-1-13",
    "wbs": "1.13",
    "name": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "notes": "หมวด optional สำหรับโครงการที่รวมงานแอร์/ระบายอากาศ",
    "categoryId": "1-13",
    "categoryName": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 231
  },
  {
    "templateId": "schedule-template-1-13-1",
    "wbs": "1.13.1",
    "name": "กำหนดตำแหน่งเครื่องปรับอากาศ ท่อน้ำทิ้ง และท่อน้ำยา",
    "notes": "",
    "categoryId": "1-13",
    "categoryName": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-13",
    "taskType": "subtask",
    "order": 232
  },
  {
    "templateId": "schedule-template-1-13-2",
    "wbs": "1.13.2",
    "name": "เดินท่อน้ำยา ท่อน้ำทิ้ง และ Sleeve สำหรับระบบปรับอากาศ",
    "notes": "",
    "categoryId": "1-13",
    "categoryName": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-13",
    "taskType": "subtask",
    "order": 233
  },
  {
    "templateId": "schedule-template-1-13-3",
    "wbs": "1.13.3",
    "name": "ติดตั้งเครื่องปรับอากาศ พัดลมดูดอากาศ หรือระบบระบายอากาศ",
    "notes": "",
    "categoryId": "1-13",
    "categoryName": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-13",
    "taskType": "subtask",
    "order": 234
  },
  {
    "templateId": "schedule-template-1-13-4",
    "wbs": "1.13.4",
    "name": "ทดสอบระบบปรับอากาศและการระบายน้ำทิ้ง",
    "notes": "",
    "categoryId": "1-13",
    "categoryName": "งานระบบปรับอากาศและระบายอากาศ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-13",
    "taskType": "subtask",
    "order": 235
  },
  {
    "templateId": "schedule-template-1-14",
    "wbs": "1.14",
    "name": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "notes": "หมวด optional สำหรับโครงการที่มีสระว่ายน้ำบนอาคาร ต้องตรวจแบบโครงสร้างและระบบกันซึมร่วมกับผู้ออกแบบก่อนเริ่มงาน",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 236
  },
  {
    "templateId": "schedule-template-1-14-1",
    "wbs": "1.14.1",
    "name": "ตรวจแบบโครงสร้างและน้ำหนักบรรทุกสระว่ายน้ำชั้น 2",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 237
  },
  {
    "templateId": "schedule-template-1-14-2",
    "wbs": "1.14.2",
    "name": "ตรวจตำแหน่งคาน พื้น เสา และแนวรับน้ำหนักบริเวณสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 238
  },
  {
    "templateId": "schedule-template-1-14-3",
    "wbs": "1.14.3",
    "name": "ตรวจค่าการแอ่นตัว รอยต่อโครงสร้าง และ joint กันน้ำตามแบบ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 239
  },
  {
    "templateId": "schedule-template-1-14-4",
    "wbs": "1.14.4",
    "name": "ตรวจตำแหน่ง sleeve, pipe penetration และ embedded item ก่อนเทคอนกรีต",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 240
  },
  {
    "templateId": "schedule-template-1-14-5",
    "wbs": "1.14.5",
    "name": "งานโครงสร้างบ่อสระและขอบสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 241
  },
  {
    "templateId": "schedule-template-1-14-6",
    "wbs": "1.14.6",
    "name": "งานระบบท่อ inlet, outlet, main drain และ overflow",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 242
  },
  {
    "templateId": "schedule-template-1-14-7",
    "wbs": "1.14.7",
    "name": "งานระบบ emergency drain และจุดระบายน้ำฉุกเฉิน",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 243
  },
  {
    "templateId": "schedule-template-1-14-8",
    "wbs": "1.14.8",
    "name": "งานห้องเครื่อง ปั๊ม ถังกรอง และอุปกรณ์ระบบสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 244
  },
  {
    "templateId": "schedule-template-1-14-9",
    "wbs": "1.14.9",
    "name": "งานเดินท่อจากสระไปห้องเครื่องและทดสอบแรงดันท่อ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 245
  },
  {
    "templateId": "schedule-template-1-14-10",
    "wbs": "1.14.10",
    "name": "งาน waterproofing พื้น ผนัง และรอยต่อรอบสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 246
  },
  {
    "templateId": "schedule-template-1-14-11",
    "wbs": "1.14.11",
    "name": "ทดสอบขังน้ำ 72 ชั่วโมง",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 247
  },
  {
    "templateId": "schedule-template-1-14-12",
    "wbs": "1.14.12",
    "name": "ตรวจรอยรั่วซึมใต้ท้องพื้น ฝ้า และพื้นที่ด้านล่าง",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 248
  },
  {
    "templateId": "schedule-template-1-14-13",
    "wbs": "1.14.13",
    "name": "งานปูกระเบื้องหรือผิวตกแต่งภายในสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 249
  },
  {
    "templateId": "schedule-template-1-14-14",
    "wbs": "1.14.14",
    "name": "งาน coping ขอบสระ และ sealant รอบรอยต่อ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 250
  },
  {
    "templateId": "schedule-template-1-14-15",
    "wbs": "1.14.15",
    "name": "งานไฟใต้น้ำ ระบบสายดิน และอุปกรณ์ป้องกันไฟรั่ว",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 251
  },
  {
    "templateId": "schedule-template-1-14-16",
    "wbs": "1.14.16",
    "name": "งานพื้นกันลื่นรอบสระ ราวกันตก และ safety edge",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 252
  },
  {
    "templateId": "schedule-template-1-14-17",
    "wbs": "1.14.17",
    "name": "งานติดตั้งอุปกรณ์หัวจ่าย ตะแกรง drain skimmer หรือ overflow gutter",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 253
  },
  {
    "templateId": "schedule-template-1-14-18",
    "wbs": "1.14.18",
    "name": "ทดสอบระบบหมุนเวียนน้ำ ระบบกรอง และปรับสมดุลน้ำ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 254
  },
  {
    "templateId": "schedule-template-1-14-19",
    "wbs": "1.14.19",
    "name": "ตรวจรับ ส่งมอบคู่มือ และแผนบำรุงรักษาระบบสระ",
    "notes": "",
    "categoryId": "1-14",
    "categoryName": "งานสระว่ายน้ำชั้น 2 (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-14",
    "taskType": "subtask",
    "order": 255
  },
  {
    "templateId": "schedule-template-1-15",
    "wbs": "1.15",
    "name": "งานระบบลิฟท์ (ถ้ามี)",
    "notes": "หมวด optional สำหรับโครงการที่มีลิฟท์ ให้ใช้ร่วมกับ shop drawing และข้อกำหนดผู้ผลิต",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 256
  },
  {
    "templateId": "schedule-template-1-15-1",
    "wbs": "1.15.1",
    "name": "ตรวจแบบ shop drawing และ specification ลิฟท์",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 257
  },
  {
    "templateId": "schedule-template-1-15-2",
    "wbs": "1.15.2",
    "name": "ตรวจขนาด shaft, pit และ overhead ตามแบบผู้ผลิต",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 258
  },
  {
    "templateId": "schedule-template-1-15-3",
    "wbs": "1.15.3",
    "name": "ตรวจงานโครงสร้างช่องลิฟท์และความดิ่งของ shaft",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 259
  },
  {
    "templateId": "schedule-template-1-15-4",
    "wbs": "1.15.4",
    "name": "งาน embedded plate, bracket และ insert สำหรับรางลิฟท์",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 260
  },
  {
    "templateId": "schedule-template-1-15-5",
    "wbs": "1.15.5",
    "name": "งานระบบไฟฟ้า main power และ grounding สำหรับลิฟท์",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 261
  },
  {
    "templateId": "schedule-template-1-15-6",
    "wbs": "1.15.6",
    "name": "งานเตรียมช่องเปิดประตูชั้นและ sill beam",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 262
  },
  {
    "templateId": "schedule-template-1-15-7",
    "wbs": "1.15.7",
    "name": "งานติดตั้ง guide rail",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 263
  },
  {
    "templateId": "schedule-template-1-15-8",
    "wbs": "1.15.8",
    "name": "งานติดตั้งประตูชั้นและวงกบลิฟท์",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 264
  },
  {
    "templateId": "schedule-template-1-15-9",
    "wbs": "1.15.9",
    "name": "งานติดตั้งเครื่องลิฟท์ controller motor หรือ machine room equipment",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 265
  },
  {
    "templateId": "schedule-template-1-15-10",
    "wbs": "1.15.10",
    "name": "งานติดตั้ง cabin และอุปกรณ์ภายใน",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 266
  },
  {
    "templateId": "schedule-template-1-15-11",
    "wbs": "1.15.11",
    "name": "งาน emergency light, intercom, alarm และระบบช่วยเหลือฉุกเฉิน",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 267
  },
  {
    "templateId": "schedule-template-1-15-12",
    "wbs": "1.15.12",
    "name": "งาน fireman switch และ interface กับระบบ fire alarm",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 268
  },
  {
    "templateId": "schedule-template-1-15-13",
    "wbs": "1.15.13",
    "name": "งานตกแต่งหน้าประตูลิฟท์แต่ละชั้น",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 269
  },
  {
    "templateId": "schedule-template-1-15-14",
    "wbs": "1.15.14",
    "name": "ทดสอบเดินเครื่อง ปรับตั้ง และ commissioning",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 270
  },
  {
    "templateId": "schedule-template-1-15-15",
    "wbs": "1.15.15",
    "name": "ตรวจรับโดยผู้เชี่ยวชาญ ส่งมอบคู่มือ ใบรับประกัน และเอกสารบำรุงรักษา",
    "notes": "",
    "categoryId": "1-15",
    "categoryName": "งานระบบลิฟท์ (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-15",
    "taskType": "subtask",
    "order": 271
  },
  {
    "templateId": "schedule-template-1-16",
    "wbs": "1.16",
    "name": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "notes": "หมวด optional สำหรับโครงการที่มีทางหนีไฟหรือข้อกำหนดความปลอดภัยเพิ่มเติม",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "",
    "taskType": "heading",
    "order": 272
  },
  {
    "templateId": "schedule-template-1-16-1",
    "wbs": "1.16.1",
    "name": "ตรวจแบบทางหนีไฟและข้อกำหนดความปลอดภัยตามกฎหมาย",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 273
  },
  {
    "templateId": "schedule-template-1-16-2",
    "wbs": "1.16.2",
    "name": "งานโครงสร้างบันไดหนีไฟและ landing",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 274
  },
  {
    "templateId": "schedule-template-1-16-3",
    "wbs": "1.16.3",
    "name": "งานพื้นกันลื่นบริเวณบันไดและทางเดินหนีไฟ",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 275
  },
  {
    "templateId": "schedule-template-1-16-4",
    "wbs": "1.16.4",
    "name": "งานราวจับและราวกันตก",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 276
  },
  {
    "templateId": "schedule-template-1-16-5",
    "wbs": "1.16.5",
    "name": "งานประตูทนไฟ",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 277
  },
  {
    "templateId": "schedule-template-1-16-6",
    "wbs": "1.16.6",
    "name": "งาน panic bar, door closer และ hardware ประตูหนีไฟ",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 278
  },
  {
    "templateId": "schedule-template-1-16-7",
    "wbs": "1.16.7",
    "name": "งานป้ายทางออกฉุกเฉิน",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 279
  },
  {
    "templateId": "schedule-template-1-16-8",
    "wbs": "1.16.8",
    "name": "งานไฟฉุกเฉินและแบตเตอรี่สำรอง",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 280
  },
  {
    "templateId": "schedule-template-1-16-9",
    "wbs": "1.16.9",
    "name": "งานระบบระบายควันหรือช่องเปิดระบายอากาศตามแบบ",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 281
  },
  {
    "templateId": "schedule-template-1-16-10",
    "wbs": "1.16.10",
    "name": "งาน fire stopping รอบช่องเปิดและงานระบบที่ทะลุผนัง/พื้น",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 282
  },
  {
    "templateId": "schedule-template-1-16-11",
    "wbs": "1.16.11",
    "name": "งานทาสีหรือเคลือบกันไฟตามแบบ",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 283
  },
  {
    "templateId": "schedule-template-1-16-12",
    "wbs": "1.16.12",
    "name": "ตรวจความกว้างทางเดิน ระยะหนีไฟ และสิ่งกีดขวาง",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 284
  },
  {
    "templateId": "schedule-template-1-16-13",
    "wbs": "1.16.13",
    "name": "ทดสอบการใช้งานประตู ทางเดิน ป้าย และไฟฉุกเฉิน",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 285
  },
  {
    "templateId": "schedule-template-1-16-14",
    "wbs": "1.16.14",
    "name": "ตรวจรับและส่งมอบงานความปลอดภัย",
    "notes": "",
    "categoryId": "1-16",
    "categoryName": "งานทางหนีไฟ / ความปลอดภัย (ถ้ามี)",
    "parentTemplateId": "schedule-template-1-16",
    "taskType": "subtask",
    "order": 286
  }
] as const satisfies readonly ScheduleTemplateTask[];
